In [2]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

C:\Users\USER\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
df = pd.read_csv("names_dataset.csv")

In [4]:
df.head()

index       name sex
0      0       Mary   F
1      1       Anna   F
2      2       Emma   F
3      3  Elizabeth   F
4      4     Minnie   F

In [5]:
df.shape

(95025, 3)

In [6]:
df.columns


Index(['index', 'name', 'sex'], dtype='object')

In [8]:
df.isnull().isnull().sum()

index    0
name     0
sex      0
dtype: int64

In [11]:
df[df.sex == 'M'].size

103275

In [12]:
df_names = df

In [13]:
df_names.sex.replace({'F':0, 'M' : 1},inplace = True)

In [15]:
df_names.sex.unique()

array([0, 1], dtype=int64)

In [17]:
X_feature = df_names['name']

In [18]:
cv  = CountVectorizer()
X = cv.fit_transform(X_feature)

In [19]:
from sklearn.model_selection import train_test_split


In [20]:
X
y = df_names.sex

In [25]:
X_train, X_test , y_train , y_test = train_test_split(X ,y , test_size = 0.2, random_state = 45 )

In [26]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)
clf.score(X_test,y_test)

0.640989213364904

In [27]:
print("Accuracy of Model: ",clf.score(X_test,y_test)*100,"%")

Accuracy of Model:  64.0989213364904 %


In [46]:
#samples
sample_name = ["Alex"]
vect = cv.transform(sample_name).toarray()

In [47]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
clf.predict(vect)

array([1], dtype=int64)